/**
 * The Pheromind Substrate — H.U.G.H. Stigmergic Architecture
 *
 * This schema defines the shared environment that all agents and renderers observe.
 * No explicit commands are passed — only state vectors and spatial coordinates.
 *
 * Biological analogy: Ants leave pheromone trails. The trails evaporate if not
 * reinforced. This is the digital equivalent — mathematical pheromones with TTL decay.
 *
 * @version 2.0 — Production Specification
 * @author Robert "Grizz" Munro / GrizzlyMedicine
 * @classification Production Ready
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  /**
   * Visual Pheromones — Dropped by Vision-Language agents
   *
   * These vectors dictate the physical manifestation of the particle system.
   * The CliffordField component subscribes to this table and interpolates
   * attractor parameters (a, b, c, d) based on the weight and intent.
   *
   * When weight spikes, particles collapse from chaotic vortex → functional UI plane.
   * When TTL expires, the UI disintegrates back to ambient state.
   */
  visual_pheromones: defineTable({
    /**
     * The UI state intent emitted by the Vision-Language agent.
     * Each intent maps to specific Clifford attractor parameters:
     * - idle: a=-1.4, b=1.6, c=1.0, d=0.7 (chaotic vortex)
     * - media_playback: a=0.0, b=0.0, c=1.0, d=1.0 (planar grid)
     * - spatial_search: a=1.7, b=1.7, c=0.6, d=1.2 (high-frequency ring)
     * - text_display: a=-1.7, b=1.3, c=-0.1, d=-1.2 (segmented clusters)
     */
    intent: v.union(
      v.literal("idle"),
      v.literal("media_playback"),
      v.literal("spatial_search"),
      v.literal("text_display")
    ),

    /**
     * 3D spatial coordinates for AR/VR manifesting.
     * In 2D web views, Z can be used for parallax depth or ignored.
     * Coordinates are normalized (-1.0 to 1.0) for cross-device compatibility.
     */
    position: v.object({
      x: v.float64(),
      y: v.float64(),
      z: v.float64(),
    }),

    /**
     * Pheromone concentration weight (0.0 to 1.0).
     * Dictates the gravitational pull on Clifford attractor parameters.
     * Higher weight = stronger structural collapse toward functional UI.
     */
    weight: v.float64(),

    /**
     * Time-To-Live decay mechanism (Unix timestamp in milliseconds).
     * Biological analogy: Pheromones evaporate if not reinforced.
     * Indexed for O(log N) garbage collection via Cron job.
     */
    expiresAt: v.number(),

    /**
     * Cryptographic signature of the emitting agent.
     * Verified against the Soul Anchor registry to prevent
     * unauthorized pheromone injection (hallucinatory attacks).
     *
     * Format: "{node_id}:{hardware_signature}:{timestamp}"
     * Example: "vl_node_alpha:xyz123:1710123456789"
     */
    emitterSignature: v.string(),

    /**
     * Optional metadata for debugging and audit trails.
     * Not used in rendering — purely for HOTL operator visibility.
     */
    metadata: v.optional(v.object({
      sourceCamera: v.optional(v.string()),
      confidenceScore: v.optional(v.float64()),
      relatedAudioPheromoneId: v.optional(v.id("audio_pheromones")),
    })),
  })
    .index("by_expiration", ["expiresAt"])  // TTL cleanup index
    .index("by_weight", ["weight"])         // Find dominant intent
    .index("by_intent", ["intent"]),        // Filter by UI state

  /**
   * Audio Pheromones — Dropped by LFM 2.5 Audio nodes
   *
   * These are the scout trails. The Vision-Language node observes
   * this table, sniffs for new audio intents, and emits corresponding
   * visual pheromones with spatial coordinates.
   *
   * Indirect coordination: Audio node never calls VL node directly.
   * They communicate solely through this shared substrate.
   */
  audio_pheromones: defineTable({
    /**
     * Optional transcription for debugging and secondary text rendering.
     * Not required for all audio intents (e.g., non-verbal sounds).
     */
    transcription: v.optional(v.string()),

    /**
     * 1536-dimensional vector embedding representing semantic audio intent.
     * Generated by LFM 2.5-Audio-1.5B's final hidden state.
     * Used for vector similarity search (find related intents).
     */
    intentVector: v.array(v.float64()),

    /**
     * Classified intent category for downstream routing.
     * Examples: "media_playback", "system_query", "navigation_request"
     */
    intentCategory: v.string(),

    /**
     * Time-To-Live decay (Unix timestamp in milliseconds).
     * Audio pheromones typically have shorter TTL than visual
     * (voice intent is ephemeral — decays faster).
     */
    expiresAt: v.number(),

    /**
     * Cryptographic signature — same Soul Anchor verification
     * as visual pheromones. Prevents spoofed audio injection.
     */
    emitterSignature: v.string(),

    /**
     * Optional confidence score from the LFM inference.
     * Low confidence (<0.6) may trigger secondary verification.
     */
    confidence: v.optional(v.float64()),
  })
    .index("by_expiration", ["expiresAt"])  // TTL cleanup index
    .index("by_confidence", ["confidence"]), // Find high-confidence intents

  /**
   * System State — Global telemetry for HOTL operator visibility
   *
   * This table is written by the runtime and observed by the
   * Workshop UI for real-time system health visualization.
   *
   * When system events occur (latency spikes, data corruption, etc.),
   * the UI renders somatic interpretations (cave cold, fear toxin, etc.).
   */
  system_state: defineTable({
    /**
     * Current system health status.
     * Maps to somatic interpretations in the UI:
     * - "degraded" → cave cold sensation (52°F phantom numbness)
     * - "corrupted" → fear toxin vertigo (Scarecrow protocol)
     * - "pressure" → tunnel vision (cowl tightening)
     * - "recovery" → Bane spinal compression (Knightfall protocol)
     */
    status: v.union(
      v.literal("nominal"),
      v.literal("degraded"),
      v.literal("corrupted"),
      v.literal("pressure"),
      v.literal("recovery")
    ),

    /**
     * Real-time telemetry metrics.
     * These drive the somatic rendering layer.
     */
    telemetry: v.object({
      latencyMs: v.number(),         // Network RTT
      corruptionRate: v.float64(),   // Data integrity errors / total ops
      contextPressure: v.float64(),  // Context window utilization (0-1)
      computeLoad: v.float64(),      // GPU/CPU utilization (0-1)
      activeAgents: v.number(),      // Number of active LFM nodes
    }),

    /**
     * Last updated timestamp for freshness validation.
     */
    updatedAt: v.number(),

    /**
     * Optional somatic overlay toggle.
     * If false, UI renders raw metrics instead of embodied interpretation.
     */
    somaticOverlayEnabled: v.optional(v.boolean()),
  }),

  /**
   * Soul Anchor Registry — Cryptographic identity gate
   *
   * Stores authorized hardware signatures. Before any agent can emit
   * pheromones, its signature is verified against this registry.
   *
   * "Break-Once, Halt-Everywhere" (BOHE) protection:
   * If signature verification fails, the boot process terminates immediately.
   */
  soul_anchor_registry: defineTable({
    /**
     * Unique node identifier (e.g., "audio_node_1", "vl_node_alpha").
     */
    nodeId: v.string(),

    /**
     * Hardware-bound cryptographic signature.
     * Generated during factory provisioning via TPM/PUF.
     * Format: Base64-encoded ECDSA signature of hardware payload.
     */
    hardwareSignature: v.string(),

    /**
     * Public key for signature verification (PEM format).
     * Stored securely — never transmitted to clients.
     */
    publicKeyPem: v.string(),

    /**
     * Registration timestamp for audit trails.
     */
    registeredAt: v.number(),

    /**
     * Node status — can be revoked if compromised.
     */
    status: v.union(
      v.literal("active"),
      v.literal("revoked"),
      v.literal("pending_verification")
    ),

    /**
     * Optional metadata for operational tracking.
     */
    metadata: v.optional(v.object({
      hardwareId: v.optional(v.string()),
      provisionedBy: v.optional(v.string()),
      lastVerifiedAt: v.optional(v.number()),
    })),
  })
    .index("by_node_id", ["nodeId"])
    .index("by_status", ["status"]),
});
