/* eslint-disable */
/**
 * Generated by convex dev — DO NOT EDIT.
 *
 * This stub enables local TypeScript compilation before first `npx convex dev`.
 * Running `npx convex dev` will regenerate this file with full type safety.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyApi = Record<string, Record<string, any>>;

const fullApi = {
  pheromones: {
    emitVisual: "pheromones:emitVisual" as any,
    emitAudio: "pheromones:emitAudio" as any,
    getLatestVisual: "pheromones:getLatestVisual" as any,
    getLatestAudio: "pheromones:getLatestAudio" as any,
    getDominantVisual: "pheromones:getDominantVisual" as any,
    getSystemState: "pheromones:getSystemState" as any,
    verifySignature: "pheromones:verifySignature" as any,
  },
};

export const api: AnyApi = fullApi;
export const internal: AnyApi = fullApi;
