/* eslint-disable */
/**
 * Generated by convex dev — DO NOT EDIT.
 *
 * This stub enables local TypeScript compilation before first `npx convex dev`.
 * Running `npx convex dev` will regenerate this file with full type safety.
 */

import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

import type { DataModelFromSchemaDefinition } from "convex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export const query = queryGeneric<DataModel>();
export const mutation = mutationGeneric<DataModel>();
export const action = actionGeneric<DataModel>();
export const httpAction = httpActionGeneric();
export const internalQuery = internalQueryGeneric<DataModel>();
export const internalMutation = internalMutationGeneric<DataModel>();
export const internalAction = internalActionGeneric<DataModel>();
